import pygame

GREETING = pygame.USEREVENT + 1
SHAPES = pygame.USEREVENT + 2
SERVER_SEND_SHAPE = pygame.USEREVENT + 3
CLIENT_SEND_SHAPE = pygame.USEREVENT + 4
CLIENT_CREATE_SHAPE = pygame.USEREVENT + 5